import { createContext, useContext, useState, type ReactNode } from "react";

type Language = "en" | "zh";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    "app.title": "NSR Route Planning System",
    "nav.scenario": "Scenario",
    "nav.workspace": "Map Workspace",
    "nav.export": "Export & Report",
    "nav.dataset": "Dataset:",
    "nav.export.btn": "Export",

    "month.july-august": "July-August 2024",
    "month.august-september": "August-September 2024",
    "month.july-october": "July-October 2024",

    "scenario.title": "Scenario Selection",
    "scenario.subtitle": "Select a time period and timestamp to begin route planning.",
    "scenario.config.title": "Dataset Configuration",
    "scenario.config.desc": "Choose the time period and specific timestamp for analysis",
    "scenario.month": "Month / Period",
    "scenario.timestamp": "Timestamp (UTC)",
    "scenario.loadLayers": "Load Layers",
    "scenario.recommended.title": "Recommended Snapshots",
    "scenario.recommended.desc": "Pre-selected references for common scenarios",

    "workspace.scenario": "Scenario",
    "workspace.startPoint": "Start Point",
    "workspace.goalPoint": "Goal Point",
    "workspace.pickOnMap": "Pick on map",
    "workspace.layers": "Layers",
    "workspace.layer.bathymetry": "Bathymetry Mask",
    "workspace.layer.ais": "AIS Corridor Heatmap",
    "workspace.layer.unet": "U-Net Zones",
    "workspace.layer.ice": "Ice Concentration",
    "workspace.layer.wave": "Wave Height",
    "workspace.layer.wind": "Wind Speed",
    "workspace.legend": "Map Legend",
    "workspace.legend.safe": "SAFE",
    "workspace.legend.safe.desc": "Navigable",
    "workspace.legend.caution": "CAUTION",
    "workspace.legend.caution.desc": "Proceed with care",
    "workspace.legend.blocked": "BLOCKED",
    "workspace.legend.blocked.desc": "Avoid",
    "workspace.legend.ais": "AIS Corridor",
    "workspace.legend.ais.desc": "Historical traffic",
    "workspace.planning": "Planning",
    "workspace.mousePosition": "Mouse Position",
    "workspace.safetyPolicy": "Safety Policy",
    "workspace.safetyPolicy.opt1": "Blocked = Bathy + U-Net Blocked",
    "workspace.safetyPolicy.opt2": "Blocked = Bathy Only",
    "workspace.safetyPolicy.opt3": "Strict (Include Caution)",
    "workspace.cautionHandling": "Caution Handling",
    "workspace.cautionHandling.opt1": "Tie-breaker (Default)",
    "workspace.cautionHandling.opt2": "Budget Constraint",
    "workspace.cautionHandling.opt3": "Minimize Exposure",
    "workspace.corridorBias": "AIS Corridor Bias",
    "workspace.planRoute": "Plan Route",
    "workspace.planRoute.loading": "Planning...",
    "workspace.infer.run": "Run U-Net Inference",
    "workspace.infer.loading": "Inferring...",
    "workspace.infer.latest": "Latest Inference",
    "workspace.pick.start.hint": "Click map to set start point",
    "workspace.pick.goal.hint": "Click map to set goal point",
    "workspace.openGallery": "Open In Gallery",

    "summary.title": "Route Summary",
    "summary.distance": "Distance",
    "summary.safe": "% in SAFE",
    "summary.caution": "% in CAUTION",
    "summary.alignment": "Corridor Alignment",
    "summary.noViolations": "No Safety Violations",
    "summary.noViolations.desc": "Route avoids all BLOCKED zones",
    "summary.planToSee": "Plan a route to see summary metrics",

    "explain.title": "Explainability",
    "explain.reason1": "Avoided all BLOCKED zones (bathymetry + U-Net predictions)",
    "explain.reason2": "Minimized total distance under safety constraints",
    "explain.reason3": "Applied mild AIS corridor preference",
    "explain.reason4": "Route segment in CAUTION zones",

    "export.title": "Gallery & Export",
    "export.subtitle": "Review saved runs, inspect metadata, download outputs.",
    "export.savedRuns": "Saved Runs",
    "export.runDetail": "Run Detail",
    "export.noItems": "No gallery items yet.",
    "export.noSelection": "No run selected",
    "export.loadingDetail": "Loading detail...",
    "export.preview": "Preview",
    "export.backtest": "AIS Backtest",
    "export.backtest.run": "Run Backtest",
    "export.backtest.loading": "Evaluating...",
    "export.downloadRoute": "Download Route GeoJSON",
    "export.downloadReport": "Download Report JSON",
    "export.downloadImage": "Download Image",
    "export.delete": "Delete",
    "export.refresh": "Refresh",

    "toast.planning": "Planning optimal route...",
    "toast.success": "Route calculated successfully",
    "toast.pickStart": "Click on the map to set start point",
    "toast.pickGoal": "Click on the map to set goal point",
    "toast.mapClicked": "Map clicked:",
    "toast.coordsCopied": "Coordinates copied to clipboard",
    "toast.invalidCoords": "Invalid coordinates",
    "toast.tsRequired": "Timestamp is required",
    "toast.planFailed": "Route planning failed",
    "toast.inferRunning": "Running U-Net inference...",
    "toast.inferDone": "Inference done",
    "toast.inferFailed": "Inference failed",
    "toast.galleryShotUpdated": "Gallery screenshot updated",
    "toast.galleryShotFallback": "Route saved, screenshot kept as backend preview",
    "toast.loadGalleryListFailed": "Failed to load gallery list",
    "toast.loadGalleryItemFailed": "Failed to load gallery item",
    "toast.galleryDeleted": "Gallery item deleted",
    "toast.deleteFailed": "Delete failed",
    "toast.noRouteGeojson": "No route geojson in this item",
    "toast.routeDownloaded": "Route GeoJSON downloaded",
    "toast.reportDownloaded": "Report JSON downloaded",
    "toast.imageDownloaded": "Image downloaded",
    "toast.backtestDone": "AIS backtest finished",
    "toast.backtestFailed": "AIS backtest failed",
  },
  zh: {
    "app.title": "NSR 航线规划系统",
    "nav.scenario": "场景选择",
    "nav.workspace": "地图工作台",
    "nav.export": "导出与报告",
    "nav.dataset": "数据集：",
    "nav.export.btn": "导出",

    "month.july-august": "2024年7-8月",
    "month.august-september": "2024年8-9月",
    "month.july-october": "2024年7-10月",

    "scenario.title": "场景选择",
    "scenario.subtitle": "选择时间段与时间片，开始航线规划。",
    "scenario.config.title": "数据集配置",
    "scenario.config.desc": "选择分析时间段和具体时间片",
    "scenario.month": "月份 / 时段",
    "scenario.timestamp": "时间戳 (UTC)",
    "scenario.loadLayers": "加载图层",
    "scenario.recommended.title": "推荐快照",
    "scenario.recommended.desc": "常见场景的预设参考",

    "workspace.scenario": "场景",
    "workspace.startPoint": "起点",
    "workspace.goalPoint": "终点",
    "workspace.pickOnMap": "地图点选",
    "workspace.layers": "图层",
    "workspace.layer.bathymetry": "水深掩膜",
    "workspace.layer.ais": "AIS 热力图",
    "workspace.layer.unet": "U-Net 分区",
    "workspace.layer.ice": "海冰浓度",
    "workspace.layer.wave": "浪高",
    "workspace.layer.wind": "风速",
    "workspace.legend": "图例",
    "workspace.legend.safe": "安全",
    "workspace.legend.safe.desc": "可通航",
    "workspace.legend.caution": "谨慎",
    "workspace.legend.caution.desc": "谨慎通过",
    "workspace.legend.blocked": "禁行",
    "workspace.legend.blocked.desc": "应避开",
    "workspace.legend.ais": "AIS 航道",
    "workspace.legend.ais.desc": "历史航迹偏好",
    "workspace.planning": "规划",
    "workspace.mousePosition": "鼠标位置",
    "workspace.safetyPolicy": "安全策略",
    "workspace.safetyPolicy.opt1": "禁行 = 水深 + U-Net 禁行",
    "workspace.safetyPolicy.opt2": "禁行 = 仅水深",
    "workspace.safetyPolicy.opt3": "严格模式（包含谨慎区）",
    "workspace.cautionHandling": "谨慎区处理",
    "workspace.cautionHandling.opt1": "平局决胜（默认）",
    "workspace.cautionHandling.opt2": "预算约束",
    "workspace.cautionHandling.opt3": "最小暴露",
    "workspace.corridorBias": "AIS 航道偏好",
    "workspace.planRoute": "规划航线",
    "workspace.planRoute.loading": "规划中...",
    "workspace.infer.run": "运行 U-Net 推理",
    "workspace.infer.loading": "推理中...",
    "workspace.infer.latest": "最新推理",
    "workspace.pick.start.hint": "点击地图设置起点",
    "workspace.pick.goal.hint": "点击地图设置终点",
    "workspace.openGallery": "在 Gallery 打开",

    "summary.title": "航线摘要",
    "summary.distance": "距离",
    "summary.safe": "安全区占比",
    "summary.caution": "谨慎区占比",
    "summary.alignment": "航道对齐度",
    "summary.noViolations": "无安全违规",
    "summary.noViolations.desc": "航线避开所有禁行区",
    "summary.planToSee": "请先规划航线以查看摘要",

    "explain.title": "可解释性",
    "explain.reason1": "避开了全部禁行区（水深 + U-Net）",
    "explain.reason2": "在安全约束下最小化总距离",
    "explain.reason3": "轻度偏好 AIS 航道",
    "explain.reason4": "航线经过部分谨慎区",

    "export.title": "Gallery 与导出",
    "export.subtitle": "查看历史规划、元数据和下载产物。",
    "export.savedRuns": "历史记录",
    "export.runDetail": "记录详情",
    "export.noItems": "暂无 Gallery 记录。",
    "export.noSelection": "未选择记录",
    "export.loadingDetail": "加载详情中...",
    "export.preview": "预览",
    "export.backtest": "AIS 回测",
    "export.backtest.run": "运行回测",
    "export.backtest.loading": "评估中...",
    "export.downloadRoute": "下载 Route GeoJSON",
    "export.downloadReport": "下载报告 JSON",
    "export.downloadImage": "下载图片",
    "export.delete": "删除",
    "export.refresh": "刷新",

    "toast.planning": "正在规划最优航线...",
    "toast.success": "航线计算成功",
    "toast.pickStart": "点击地图设置起点",
    "toast.pickGoal": "点击地图设置终点",
    "toast.mapClicked": "地图点击：",
    "toast.coordsCopied": "坐标已复制",
    "toast.invalidCoords": "坐标格式无效",
    "toast.tsRequired": "需要先选择时间片",
    "toast.planFailed": "航线规划失败",
    "toast.inferRunning": "正在运行 U-Net 推理...",
    "toast.inferDone": "推理完成",
    "toast.inferFailed": "推理失败",
    "toast.galleryShotUpdated": "Gallery 截图已更新",
    "toast.galleryShotFallback": "已保存航线，截图保留后端预览",
    "toast.loadGalleryListFailed": "加载 Gallery 列表失败",
    "toast.loadGalleryItemFailed": "加载 Gallery 详情失败",
    "toast.galleryDeleted": "Gallery 记录已删除",
    "toast.deleteFailed": "删除失败",
    "toast.noRouteGeojson": "该记录缺少 route geojson",
    "toast.routeDownloaded": "Route GeoJSON 已下载",
    "toast.reportDownloaded": "报告 JSON 已下载",
    "toast.imageDownloaded": "图片已下载",
    "toast.backtestDone": "AIS 回测完成",
    "toast.backtestFailed": "AIS 回测失败",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");
  const t = (key: string): string => translations[language][key] || key;
  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
